// Auto-generated module split from dist source.
  const state = {
    ready: false,
    drawerOpen: false,
    activeTab: "tournament",
    lastFocused: null,
    notice: { type: "info", message: "" },
    noticeTimer: null,
    saveTimer: null,
    host: null,
    shadowRoot: null,
    patchedHistory: null,
    routeKey: routeKey(),
    store: createDefaultStore(),
    bracket: {
      iframe: null,
      ready: false,
      failed: false,
      timeoutHandle: null,
      frameHeight: 0,
      lastError: "",
    },
    autoDetect: {
      observer: null,
      queued: false,
      lastScanAt: 0,
      lastFingerprint: "",
    },
    apiAutomation: {
      syncing: false,
      startingMatchId: "",
      authBackoffUntil: 0,
      lastAuthNoticeAt: 0,
      authToken: "",
      authTokenExpiresAt: 0,
      authTokenSource: "",
      authRefreshPromise: null,
      authHeaderCaptureInstalled: false,
      authHeaderBridgeInjected: false,
    },
    matchReturnShortcut: {
      root: null,
      syncing: false,
      inlineSyncingByLobby: {},
      inlineOutcomeByLobby: {},
      pendingConfirmationByLobby: {},
      pendingDrawUnlockOverride: null,
    },
    updateStatus: {
      capable: false,
      status: "idle",
      installedVersion: "",
      remoteVersion: "",
      available: false,
      checkedAt: 0,
      sourceUrl: "",
      downloadUrl: USERSCRIPT_DOWNLOAD_URL,
      error: "",
      stale: false,
      validators: {},
    },
    updateStatusSignature: "",
    updateCheckPromise: null,
    runtimeStatusSignature: "",
    cleanupStack: [],
  };


